post:
  print:
    method: "post"
    body: "subtitution 1"
    url: "http://localhost:2300/api/print/>"
    headers:
      content_type: "text/plain"
      content_disposition: "attachment; filename*=UTF-8''test_1.txt"
      connection: "close"
      transfer_encoding: "chunked"
  print_task: {}
get: {}
put: {}
patch: {}
delete: {}
